### ISSUE TITLE
Multi platform compilation problem

### ISSUE THREAD

**Issue by earthloong** [XDagger/QtXdagWallet#5]
For multiple platforms (Windows, MacOS, Linux, etc.) compiled, many.Pro engineering files are used at present. This method is not conducive to the maintenance and management of code. It is suggested that a single.Pro engineering file should be used to manage it.

**Comment by earthloong** [comment]
PR：https://github.com/XDagger/QtXdagWallet/pull/4

**Comment by xrdavies** [comment]
Thank you.
